version: "3.8"

services:
  webserver:
    container_name: example-webserver
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    ports:
      - ":9000"
    volumes:
      - ./:/var/www/html
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - "/tmp/xdebug:/tmp/xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"
